In [1]:
import pandas as pd
import numpy as np

In [2]:
# Import dataset
df = pd.read_csv('exoplanets_2018.csv')
# Select top of the dataset
df.shape

(9564, 49)

In [15]:
# Analysing type of data
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7803 entries, 0 to 9563
Data columns (total 39 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   DispositionScore                                7803 non-null   float64
 1   OrbitalPeriod[days]                             7803 non-null   float64
 2   OrbitalPeriodUpperUnc.[days]                    7803 non-null   float64
 3   OrbitalPeriodLowerUnc.[days]                    7803 non-null   float64
 4   TransitEpoch[BKJD]                              7803 non-null   float64
 5   TransitEpochUpperUnc.[BKJD]                     7803 non-null   float64
 6   TransitEpochLowerUnc.[BKJD]                     7803 non-null   float64
 7   ImpactParameter                                 7803 non-null   float64
 8   ImpactParameterUpperUnc.                        7803 non-null   float64
 9   ImpactParameterLowerUnc.                        7803 non-null   float64
 10  TransitDuration[hrs]                            7803 non-null   float64
 11  TransitDurationUpperUnc.[hrs]                   7803 non-null   float64
 12  TransitDurationLowerUnc.[hrs]                   7803 non-null   float64
 13  TransitDepth[ppm]                               7803 non-null   float64
 14  TransitDepthUpperUnc.[ppm]                      7803 non-null   float64
 15  TransitDepthLowerUnc.[ppm]                      7803 non-null   float64
 16  PlanetaryRadius[Earthradii]                     7803 non-null   float64
 17  PlanetaryRadiusUpperUnc.[Earthradii]            7803 non-null   float64
 18  PlanetaryRadiusLowerUnc.[Earthradii]            7803 non-null   float64
 19  EquilibriumTemperature[K]                       7803 non-null   float64
 20  InsolationFlux[Earthflux]                       7803 non-null   float64
 21  InsolationFluxUpperUnc.[Earthflux]              7803 non-null   float64
 22  InsolationFluxLowerUnc.[Earthflux]              7803 non-null   float64
 23  TransitSignal-to-Noise                          7803 non-null   float64
 24  TCEPlanetNumber                                 7803 non-null   float64
 25  StellarEffectiveTemperature[K]                  7803 non-null   float64
 26  StellarEffectiveTemperatureUpperUnc.[K]         7803 non-null   float64
 27  StellarEffectiveTemperatureLowerUnc.[K]         7803 non-null   float64
 28  StellarSurfaceGravity[log10(cm/s**2)]           7803 non-null   float64
 29  StellarSurfaceGravityUpperUnc.[log10(cm/s**2)]  7803 non-null   float64
 30  StellarSurfaceGravityLowerUnc.[log10(cm/s**2)]  7803 non-null   float64
 31  StellarRadius[Solarradii]                       7803 non-null   float64
 32  StellarRadiusUpperUnc.[Solarradii]              7803 non-null   float64
 33  StellarRadiusLowerUnc.[Solarradii]              7803 non-null   float64
 34  RA[decimaldegrees]                              7803 non-null   float64
 35  Dec[decimaldegrees]                             7803 non-null   float64
 36  Kepler-band[mag]                                7803 non-null   float64
 37  ExoplanetCandidate                              7803 non-null   int64
 38  ExoplanetConfirmed                              7803 non-null   int64
dtypes: float64(37), int64(2)
memory usage: 2.4 MB

In [4]:
# Importing columns_meaning data
col_meaning = pd.read_csv('columns_meaning.csv')
# Selecting top of col_meaning
col_meaning.head()

,# This file was produced by the NASA Exoplanet Archive http://exoplanetarchive.ipac.caltech.edu,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,# Sun Nov 15 16:51:51 2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,# COLUMN kepid: KepID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,# COLUMN kepoi_name: KOI Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,# COLUMN kepler_name: Kepler Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Cleaning col_meaning data
column = col_meaning.columns[0]
col_meaning = col_meaning[column].dropna()
col_meaning.head()
col_meaning = col_meaning[2:]

In [6]:
# Renaming Columns for better understanding of dataset (optional)
renamed_col = {}
for name in col_meaning:
    new_name = name.replace('#','').replace(' ','').replace('COLUMN','').split(':')
    renamed_col[new_name[0]] = new_name[1]
df = df.rename(columns=renamed_col)

In [7]:
# Viewing new dataset
df.head()

,KepID,KOIName,KeplerName,ExoplanetArchiveDisposition,DispositionUsingKeplerData,DispositionScore,NotTransit-LikeFalsePositiveFlag,StellarEclipseFalsePositiveFlag,CentroidOffsetFalsePositiveFlag,EphemerisMatchIndicatesContaminationFalsePositiveFlag,...,StellarEffectiveTemperatureLowerUnc.[K],StellarSurfaceGravity[log10(cm/s**2)],StellarSurfaceGravityUpperUnc.[log10(cm/s**2)],StellarSurfaceGravityLowerUnc.[log10(cm/s**2)],StellarRadius[Solarradii],StellarRadiusUpperUnc.[Solarradii],StellarRadiusLowerUnc.[Solarradii],RA[decimaldegrees],Dec[decimaldegrees],Kepler-band[mag]
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0,0,0,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [8]:
# Creating numerical class of categorical data
df['ExoplanetCandidate'] = df['DispositionUsingKeplerData'].apply(lambda x: 1 if x == 'CANDIDATE' else 0)
df['ExoplanetConfirmed'] = df['ExoplanetArchiveDisposition'].apply(lambda x: 2 if x == 'CONFIRMED' else 1 if x == 'CANDIDATE' else 0 )

In [9]:
# Viewing new dataset
df.head()

,KepID,KOIName,KeplerName,ExoplanetArchiveDisposition,DispositionUsingKeplerData,DispositionScore,NotTransit-LikeFalsePositiveFlag,StellarEclipseFalsePositiveFlag,CentroidOffsetFalsePositiveFlag,EphemerisMatchIndicatesContaminationFalsePositiveFlag,...,StellarSurfaceGravityUpperUnc.[log10(cm/s**2)],StellarSurfaceGravityLowerUnc.[log10(cm/s**2)],StellarRadius[Solarradii],StellarRadiusUpperUnc.[Solarradii],StellarRadiusLowerUnc.[Solarradii],RA[decimaldegrees],Dec[decimaldegrees],Kepler-band[mag],ExoplanetCandidate,ExoplanetConfirmed
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1,2
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,...,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1,2
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0,0,0,0,...,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436,1,1
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,...,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597,0,0
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509,1,2

In [10]:
# Removing unnecessary columns
df.drop(columns=['KeplerName',
                 'KOIName',
                 'EquilibriumTemperatureUpperUnc.[K]',
                 'KepID',
                 'ExoplanetArchiveDisposition',
                 'DispositionUsingKeplerData',
                 'NotTransit-LikeFalsePositiveFlag',
                 'StellarEclipseFalsePositiveFlag',
                 'CentroidOffsetFalsePositiveFlag',
                 'EphemerisMatchIndicatesContaminationFalsePositiveFlag',
                 'TCEDelivery',
                 'EquilibriumTemperatureLowerUnc.[K]'],
        inplace=True)

In [11]:
#Checking which column has null values
df.isna().any()

DispositionScore                                   True
OrbitalPeriod[days]                               False
OrbitalPeriodUpperUnc.[days]                       True
OrbitalPeriodLowerUnc.[days]                       True
TransitEpoch[BKJD]                                False
TransitEpochUpperUnc.[BKJD]                        True
TransitEpochLowerUnc.[BKJD]                        True
ImpactParameter                                    True
ImpactParameterUpperUnc.                           True
ImpactParameterLowerUnc.                           True
TransitDuration[hrs]                              False
TransitDurationUpperUnc.[hrs]                      True
TransitDurationLowerUnc.[hrs]                      True
TransitDepth[ppm]                                  True
TransitDepthUpperUnc.[ppm]                         True
TransitDepthLowerUnc.[ppm]                         True
PlanetaryRadius[Earthradii]                        True
PlanetaryRadiusUpperUnc.[Earthradii]               True
PlanetaryRadiusLowerUnc.[Earthradii]               True
EquilibriumTemperature[K]                          True
InsolationFlux[Earthflux]                          True
InsolationFluxUpperUnc.[Earthflux]                 True
InsolationFluxLowerUnc.[Earthflux]                 True
TransitSignal-to-Noise                             True
TCEPlanetNumber                                    True
StellarEffectiveTemperature[K]                     True
StellarEffectiveTemperatureUpperUnc.[K]            True
StellarEffectiveTemperatureLowerUnc.[K]            True
StellarSurfaceGravity[log10(cm/s**2)]              True
StellarSurfaceGravityUpperUnc.[log10(cm/s**2)]     True
StellarSurfaceGravityLowerUnc.[log10(cm/s**2)]     True
StellarRadius[Solarradii]                          True
StellarRadiusUpperUnc.[Solarradii]                 True
StellarRadiusLowerUnc.[Solarradii]                 True
RA[decimaldegrees]                                False
Dec[decimaldegrees]                               False
Kepler-band[mag]                                   True
ExoplanetCandidate                                False
ExoplanetConfirmed                                False
dtype: bool

In [12]:
# Deleting Rows with null values
df.dropna(inplace=True)
# Checking Size on new dataset
df.shape

(7803, 39)

In [13]:
# Preparing our data to feed our model
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

clean_dataset(df)

,DispositionScore,OrbitalPeriod[days],OrbitalPeriodUpperUnc.[days],OrbitalPeriodLowerUnc.[days],TransitEpoch[BKJD],TransitEpochUpperUnc.[BKJD],TransitEpochLowerUnc.[BKJD],ImpactParameter,ImpactParameterUpperUnc.,ImpactParameterLowerUnc.,...,StellarSurfaceGravityUpperUnc.[log10(cm/s**2)],StellarSurfaceGravityLowerUnc.[log10(cm/s**2)],StellarRadius[Solarradii],StellarRadiusUpperUnc.[Solarradii],StellarRadiusLowerUnc.[Solarradii],RA[decimaldegrees],Dec[decimaldegrees],Kepler-band[mag],ExoplanetCandidate,ExoplanetConfirmed
0,1.000,9.488036,2.780000e-05,-2.780000e-05,170.538750,0.002160,-0.002160,0.146,0.318,-0.146,...,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1.0,2.0
1,0.969,54.418383,2.480000e-04,-2.480000e-04,162.513840,0.003520,-0.003520,0.586,0.059,-0.443,...,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1.0,2.0
2,0.000,19.899140,1.490000e-05,-1.490000e-05,175.850252,0.000581,-0.000581,0.969,5.126,-0.077,...,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436,1.0,1.0
3,0.000,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,-0.000115,1.276,0.115,-0.092,...,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597,0.0,0.0
4,1.000,2.525592,3.760000e-06,-3.760000e-06,171.595550,0.001130,-0.001130,0.701,0.235,-0.478,...,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9559,0.000,0.527699,1.160000e-07,-1.160000e-07,131.705093,0.000170,-0.000170,1.252,0.051,-0.049,...,0.035,-0.196,0.903,0.237,-0.079,297.18875,47.093819,14.082,0.0,0.0
9560,0.497,1.739849,1.780000e-05,-1.780000e-05,133.001270,0.007690,-0.007690,0.043,0.423,-0.043,...,0.056,-0.224,1.031,0.341,-0.114,286.50937,47.163219,14.757,1.0,1.0
9561,0.021,0.681402,2.430000e-06,-2.430000e-06,132.181750,0.002850,-0.002850,0.147,0.309,-0.147,...,0.056,-0.224,1.041,0.341,-0.114,294.16489,47.176281,15.385,0.0,0.0
9562,0.092,333.486169,4.240000e-03,-4.240000e-03,153.615010,0.005070,-0.005070,0.214,0.255,-0.214,...,0.030,-0.027,7.824,0.223,-1.896,296.76288,47.145142,10.998,1.0,1.0
9563,0.000,4.856035,6.360000e-05,-6.360000e-05,135.993300,0.010800,-0.010800,0.134,0.323,-0.134,...,0.054,-0.216,1.193,0.410,-0.137,297.00977,47.121021,14.826,0.0,0.0

In [14]:
# Saving cleaned data to csv
df.to_csv('DATA.csv',index=False)